version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./app/:/usr/scr/app
    ports:
      - 9998:8000
    env_file:
      - ./app/.env.dev
