version: '3.7'

services:
  web:
    image: news_ogc_web 
    build: 
        context: ./app
        dockerfile: Dockerfile.prod
    command: gunicorn news_ogc.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/app/web/staticfiles
    networks:
      - geoserver_geo-net
    expose:
    - 8000
    env_file:
      - ./app/.env.prod
  nginx:
    image: news_ogc_nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    networks:
      - geoserver_geo-net
    ports:
      - 1337:80
    depends_on:
      - web
networks:
  geoserver_geo-net:

volumes:
    static_volume:
