version: '3.7'

services:
  web:
    build: 
        context: ./app
        dockerfile: Dockerfile.prod
    command: gunicorn news_ogc.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/app/web/staticfiles
    networks:
      - geoserver_geo-net
    ports:
      - 9998:8000
    env_file:
      - ./app/.env.prod
networks:
  geoserver_geo-net:
    external: true

volumes:
    static_volume:
